-- TradeFlow baseline schema (spec §7). Flyway runs this exactly once on first startup
-- and records it in flyway_schema_history. NEVER edit this file after it has been applied —
-- add a new V2__*.sql instead (Concept 4).
--
-- Conventions: all timestamps are TIMESTAMPTZ (stored UTC). Every tenant-scoped table carries
-- tenant_id and is indexed on it. UUID primary keys are generated by the application.

-- 7.1 tenants -------------------------------------------------------------------------------
CREATE TABLE tenants (
    id                    UUID         PRIMARY KEY,
    name                  VARCHAR(120) NOT NULL UNIQUE,
    status                VARCHAR(16)  NOT NULL DEFAULT 'ACTIVE'  CHECK (status IN ('ACTIVE', 'INACTIVE')),
    risk_mode             VARCHAR(16)  NOT NULL DEFAULT 'MONITOR' CHECK (risk_mode IN ('BLOCK', 'MONITOR')),
    rate_limit_per_window INT          NOT NULL DEFAULT 100,
    rate_window_seconds   INT          NOT NULL DEFAULT 10,
    created_at            TIMESTAMPTZ  NOT NULL DEFAULT now()
);

-- 7.2 users ---------------------------------------------------------------------------------
CREATE TABLE users (
    id            UUID         PRIMARY KEY,
    tenant_id     UUID         NOT NULL REFERENCES tenants (id),
    email         VARCHAR(160) NOT NULL,
    password_hash VARCHAR(100) NOT NULL,
    role          VARCHAR(16)  NOT NULL CHECK (role IN ('TRADER', 'RISK_MANAGER', 'ADMIN')),
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT uq_users_tenant_email UNIQUE (tenant_id, email)
);
CREATE INDEX idx_users_tenant ON users (tenant_id);

-- 7.3 instruments ---------------------------------------------------------------------------
CREATE TABLE instruments (
    id             UUID          PRIMARY KEY,
    tenant_id      UUID          NOT NULL REFERENCES tenants (id),
    symbol         VARCHAR(40)   NOT NULL,
    position_limit BIGINT        NOT NULL,
    mark_price     NUMERIC(18, 4),
    created_at     TIMESTAMPTZ   NOT NULL DEFAULT now(),
    CONSTRAINT uq_instruments_tenant_symbol UNIQUE (tenant_id, symbol)
);
CREATE INDEX idx_instruments_tenant ON instruments (tenant_id);

-- 7.4 trades --------------------------------------------------------------------------------
CREATE TABLE trades (
    id                UUID          PRIMARY KEY,
    tenant_id         UUID          NOT NULL REFERENCES tenants (id),
    user_id           UUID          NOT NULL REFERENCES users (id),
    instrument_symbol VARCHAR(40)   NOT NULL,
    side              VARCHAR(4)    NOT NULL CHECK (side IN ('BUY', 'SELL')),
    quantity          BIGINT        NOT NULL CHECK (quantity > 0),
    price             NUMERIC(18, 4) NOT NULL CHECK (price > 0),
    status            VARCHAR(16)   NOT NULL CHECK (status IN ('ACCEPTED', 'REJECTED')),
    idempotency_key   VARCHAR(80),
    submitted_at      TIMESTAMPTZ   NOT NULL
);
CREATE INDEX idx_trades_tenant_symbol ON trades (tenant_id, instrument_symbol);
CREATE INDEX idx_trades_tenant_time   ON trades (tenant_id, submitted_at);
-- Postgres treats NULLs as distinct, so trades without an idempotency key are not blocked.
CREATE UNIQUE INDEX uq_trades_tenant_idem ON trades (tenant_id, idempotency_key);

-- 7.5 outbox (transactional outbox, DD-03) --------------------------------------------------
CREATE TABLE outbox (
    id             UUID        PRIMARY KEY,
    aggregate_type VARCHAR(40) NOT NULL,
    aggregate_id   UUID        NOT NULL,
    topic          VARCHAR(60) NOT NULL,
    payload        JSONB       NOT NULL,
    status         VARCHAR(16) NOT NULL DEFAULT 'PENDING' CHECK (status IN ('PENDING', 'DISPATCHED')),
    created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    dispatched_at  TIMESTAMPTZ
);
-- Lets the relay efficiently poll undispatched rows in order.
CREATE INDEX idx_outbox_pending ON outbox (status, created_at);

-- 7.6 risk_breaches -------------------------------------------------------------------------
CREATE TABLE risk_breaches (
    id                UUID        PRIMARY KEY,
    tenant_id         UUID        NOT NULL REFERENCES tenants (id),
    trade_id          UUID        NOT NULL,
    instrument_symbol VARCHAR(40) NOT NULL,
    net_position      BIGINT      NOT NULL,
    position_limit    BIGINT      NOT NULL,
    detected_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    -- Idempotency: re-processing the same trade event cannot create a duplicate breach (FR-RISK-03).
    CONSTRAINT uq_breaches_tenant_trade UNIQUE (tenant_id, trade_id)
);
CREATE INDEX idx_breaches_tenant ON risk_breaches (tenant_id);

-- 7.7 pnl_snapshots -------------------------------------------------------------------------
CREATE TABLE pnl_snapshots (
    id                UUID          PRIMARY KEY,
    tenant_id         UUID          NOT NULL REFERENCES tenants (id),
    snapshot_date     DATE          NOT NULL,
    instrument_symbol VARCHAR(40)   NOT NULL,
    realized_pnl      NUMERIC(20, 4) NOT NULL,
    unrealized_pnl    NUMERIC(20, 4) NOT NULL,
    net_position      BIGINT        NOT NULL,
    avg_cost          NUMERIC(18, 4) NOT NULL,
    created_at        TIMESTAMPTZ   NOT NULL DEFAULT now(),
    -- Supports idempotent batch re-run via UPSERT (FR-PNL-05).
    CONSTRAINT uq_pnl_tenant_date_symbol UNIQUE (tenant_id, snapshot_date, instrument_symbol)
);
CREATE INDEX idx_pnl_tenant ON pnl_snapshots (tenant_id);

-- 7.8 alerts --------------------------------------------------------------------------------
CREATE TABLE alerts (
    id         UUID        PRIMARY KEY,
    tenant_id  UUID        NOT NULL REFERENCES tenants (id),
    type       VARCHAR(30) NOT NULL,
    message    TEXT        NOT NULL,
    payload    JSONB,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    read_at    TIMESTAMPTZ
);
CREATE INDEX idx_alerts_tenant ON alerts (tenant_id);
